"""Static reference data for the city/state scrape-target dropdowns on the dashboard."""
from __future__ import annotations

# (abbreviation, full name), sorted alphabetically by full state name — drives the state <select>.
US_STATES: list[tuple[str, str]] = [
    ("AL", "Alabama"),
    ("AK", "Alaska"),
    ("AZ", "Arizona"),
    ("AR", "Arkansas"),
    ("CA", "California"),
    ("CO", "Colorado"),
    ("CT", "Connecticut"),
    ("DE", "Delaware"),
    ("FL", "Florida"),
    ("GA", "Georgia"),
    ("HI", "Hawaii"),
    ("ID", "Idaho"),
    ("IL", "Illinois"),
    ("IN", "Indiana"),
    ("IA", "Iowa"),
    ("KS", "Kansas"),
    ("KY", "Kentucky"),
    ("LA", "Louisiana"),
    ("ME", "Maine"),
    ("MD", "Maryland"),
    ("MA", "Massachusetts"),
    ("MI", "Michigan"),
    ("MN", "Minnesota"),
    ("MS", "Mississippi"),
    ("MO", "Missouri"),
    ("MT", "Montana"),
    ("NE", "Nebraska"),
    ("NV", "Nevada"),
    ("NH", "New Hampshire"),
    ("NJ", "New Jersey"),
    ("NM", "New Mexico"),
    ("NY", "New York"),
    ("NC", "North Carolina"),
    ("ND", "North Dakota"),
    ("OH", "Ohio"),
    ("OK", "Oklahoma"),
    ("OR", "Oregon"),
    ("PA", "Pennsylvania"),
    ("RI", "Rhode Island"),
    ("SC", "South Carolina"),
    ("SD", "South Dakota"),
    ("TN", "Tennessee"),
    ("TX", "Texas"),
    ("UT", "Utah"),
    ("VT", "Vermont"),
    ("VA", "Virginia"),
    ("WA", "Washington"),
    ("WV", "West Virginia"),
    ("WI", "Wisconsin"),
    ("WY", "Wyoming"),
]

# 2-letter state abbreviation -> largest cities in that state, ordered largest-to-smallest by
# population (top 20-25 per state). Plain city names only, no state suffix, no population numbers.
STATE_CITIES: dict[str, list[str]] = {
    "AL": [
        "Huntsville", "Mobile", "Birmingham", "Montgomery", "Tuscaloosa", "Hoover", "Auburn",
        "Dothan", "Madison", "Decatur", "Florence", "Prattville", "Phenix City", "Vestavia Hills",
        "Opelika", "Athens", "Alabaster", "Gadsden", "Daphne", "Foley", "Northport", "Enterprise",
        "Homewood", "Trussville", "Fairhope",
    ],
    "AK": [
        "Anchorage", "Juneau", "Fairbanks", "Knik-Fairview", "Badger", "North Lakes", "College",
        "Wasilla", "Tanaina", "Meadow Lakes", "Sitka", "Kalifornsky", "Kenai", "Ketchikan",
        "South Lakes", "Sterling", "Gateway", "Palmer", "Bethel", "Homer", "Chena Ridge",
        "Steele Creek", "Fishhook", "Kodiak", "Farmers Loop",
    ],
    "AZ": [
        "Phoenix", "Tucson", "Mesa", "Gilbert", "Chandler", "Glendale", "Scottsdale", "Peoria",
        "Tempe", "Surprise", "Buckeye", "Goodyear", "San Tan Valley", "Yuma", "Avondale",
        "Queen Creek", "Maricopa", "Flagstaff", "Casa Grande", "Casas Adobes", "Marana",
        "Lake Havasu City", "Prescott Valley", "Catalina Foothills", "Prescott",
    ],
    "AR": [
        "Little Rock", "Fayetteville", "Springdale", "Fort Smith", "Jonesboro", "Rogers",
        "Conway", "North Little Rock", "Bentonville", "Benton", "Hot Springs", "Pine Bluff",
        "Bella Vista", "Sherwood", "Paragould", "Russellville", "Jacksonville", "Texarkana",
        "Centerton", "Cabot", "Van Buren", "Searcy", "Bryant", "West Memphis", "Siloam Springs",
    ],
    "CA": [
        "Los Angeles", "San Diego", "San Jose", "San Francisco", "Fresno", "Sacramento",
        "Long Beach", "Oakland", "Bakersfield", "Anaheim", "Stockton", "Riverside", "Irvine",
        "Santa Ana", "Chula Vista", "Santa Clarita", "Fremont", "Fontana", "San Bernardino",
        "Modesto", "Moreno Valley", "Oxnard", "Huntington Beach", "Ontario", "Elk Grove",
    ],
    "CO": [
        "Denver", "Colorado Springs", "Aurora", "Fort Collins", "Lakewood", "Thornton", "Arvada",
        "Greeley", "Westminster", "Pueblo", "Centennial", "Boulder", "Highlands Ranch",
        "Longmont", "Castle Rock", "Loveland", "Broomfield", "Commerce City", "Grand Junction",
        "Parker", "Brighton", "Littleton", "Windsor", "Erie", "Security-Widefield",
    ],
    "CT": [
        "Bridgeport", "New Haven", "Stamford", "Hartford", "Waterbury", "Norwalk", "Danbury",
        "New Britain", "Fairfield", "Greenwich", "West Hartford", "Bristol", "Hamden", "Meriden",
        "Manchester", "West Haven", "Stratford", "East Hartford", "Middletown", "Southington",
        "Wallingford", "Shelton", "Enfield", "Norwich", "Groton",
    ],
    "DE": [
        "Wilmington", "Dover", "Newark", "Middletown", "Bear", "Glasgow", "Brookside", "Milford",
        "Hockessin", "Smyrna", "Pike Creek Valley", "Claymont", "Seaford", "Georgetown",
        "North Star", "Millsboro", "Wilmington Manor", "Pike Creek", "Edgemoor", "Elsmere",
        "New Castle", "Laurel", "Clayton", "Rising Sun-Lebanon", "Camden",
    ],
    "FL": [
        "Jacksonville", "Miami", "Tampa", "Orlando", "Port St. Lucie", "St. Petersburg",
        "Cape Coral", "Hialeah", "Tallahassee", "Fort Lauderdale", "Pembroke Pines", "Hollywood",
        "Palm Bay", "Gainesville", "Miramar", "Coral Springs", "Lehigh Acres", "West Palm Beach",
        "Lakeland", "Spring Hill", "Brandon", "Pompano Beach", "Riverview", "Miami Gardens",
        "Clearwater",
    ],
    "GA": [
        "Atlanta", "Augusta", "Columbus", "Macon-Bibb County", "Savannah", "Athens",
        "South Fulton", "Sandy Springs", "Roswell", "Warner Robins", "Johns Creek", "Mableton",
        "Alpharetta", "Albany", "Marietta", "Stonecrest", "Brookhaven", "Smyrna", "Valdosta",
        "Dunwoody", "Gainesville", "Newnan", "Douglasville", "Peachtree Corners", "Canton",
    ],
    "HI": [
        "Honolulu", "East Honolulu", "Hilo", "Pearl City", "Waipahu", "Kailua", "Kaneohe",
        "Ewa Gentry", "Mililani Town", "Kahului", "Kapolei", "Kailua-Kona", "Kihei",
        "Mililani Mauka", "Makakilo", "Ocean Pointe", "Wahiawa", "Schofield Barracks", "Wailuku",
        "Ewa Beach", "Waimalu", "Halawa",
    ],
    "ID": [
        "Boise", "Meridian", "Nampa", "Caldwell", "Idaho Falls", "Pocatello", "Coeur d'Alene",
        "Twin Falls", "Post Falls", "Rexburg", "Eagle", "Lewiston", "Kuna", "Moscow", "Star",
        "Ammon", "Hayden", "Chubbuck", "Mountain Home", "Rathdrum", "Jerome", "Blackfoot",
        "Garden City", "Middleton", "Burley",
    ],
    "IL": [
        "Chicago", "Aurora", "Naperville", "Joliet", "Rockford", "Elgin", "Springfield", "Peoria",
        "Champaign", "Waukegan", "Cicero", "Bloomington", "Schaumburg", "Evanston",
        "Arlington Heights", "Bolingbrook", "Decatur", "Skokie", "Palatine", "Des Plaines",
        "Orland Park", "Oak Lawn", "Mount Prospect", "Tinley Park", "Berwyn",
    ],
    "IN": [
        "Indianapolis", "Fort Wayne", "Evansville", "Carmel", "Fishers", "South Bend",
        "Bloomington", "Noblesville", "Hammond", "Lafayette", "Greenwood", "Westfield", "Gary",
        "Muncie", "Kokomo", "Terre Haute", "Anderson", "Jeffersonville", "Elkhart", "Columbus",
        "Mishawaka", "Lawrence", "West Lafayette", "Plainfield", "Portage",
    ],
    "IA": [
        "Des Moines", "Cedar Rapids", "Davenport", "Sioux City", "Ankeny", "Iowa City",
        "West Des Moines", "Ames", "Waterloo", "Council Bluffs", "Dubuque", "Urbandale",
        "Marion", "Cedar Falls", "Bettendorf", "Waukee", "Marshalltown", "Mason City", "Ottumwa",
        "Johnston", "Fort Dodge", "Coralville", "Clinton", "Altoona", "Burlington",
    ],
    "KS": [
        "Wichita", "Overland Park", "Kansas City", "Olathe", "Topeka", "Lawrence", "Shawnee",
        "Lenexa", "Manhattan", "Salina", "Hutchinson", "Leavenworth", "Leawood", "Dodge City",
        "Garden City", "Derby", "Gardner", "Emporia", "Prairie Village", "Junction City", "Hays",
        "Pittsburg", "Liberal", "Newton", "Andover",
    ],
    "KY": [
        "Louisville", "Lexington", "Bowling Green", "Owensboro", "Covington", "Richmond",
        "Georgetown", "Elizabethtown", "Nicholasville", "Florence", "Independence",
        "Hopkinsville", "Jeffersontown", "Frankfort", "Henderson", "Paducah", "Radcliff",
        "Ashland", "Erlanger", "Winchester", "Madisonville", "Mount Washington", "Murray",
        "Shelbyville", "Burlington",
    ],
    "LA": [
        "New Orleans", "Baton Rouge", "Shreveport", "Metairie", "Lafayette", "Lake Charles",
        "Kenner", "Bossier City", "Monroe", "Alexandria", "Prairieville", "Marrero", "Houma",
        "Central", "Slidell", "Laplace", "Terrytown", "New Iberia", "Hammond", "Chalmette",
        "Bayou Cane", "Ruston", "Harvey", "Zachary", "Youngsville",
    ],
    "ME": [
        "Portland", "Lewiston", "Bangor", "South Portland", "Auburn", "Scarborough", "Brunswick",
        "Sanford", "Biddeford", "Westbrook", "Saco", "Windham", "Gorham", "Augusta", "Waterville",
        "York", "Falmouth", "Orono", "Kennebunk", "Wells", "Kittery", "Standish", "Topsham",
        "Lisbon", "Cape Elizabeth",
    ],
    "MD": [
        "Baltimore", "Columbia", "Frederick", "Germantown", "Waldorf", "Silver Spring",
        "Ellicott City", "Glen Burnie", "Gaithersburg", "Bethesda", "Rockville", "Dundalk",
        "Severn", "Bel Air South", "Bowie", "Towson", "Aspen Hill", "Wheaton", "North Bethesda",
        "Odenton", "Potomac", "Hagerstown", "Catonsville", "Woodlawn", "Essex",
    ],
    "MA": [
        "Boston", "Worcester", "Springfield", "Cambridge", "Lowell", "Brockton", "Lynn",
        "Quincy", "New Bedford", "Fall River", "Newton", "Lawrence", "Somerville", "Framingham",
        "Plymouth", "Haverhill", "Malden", "Waltham", "Brookline", "Taunton", "Revere", "Medford",
        "Weymouth", "Everett", "Peabody",
    ],
    "MI": [
        "Detroit", "Grand Rapids", "Warren", "Sterling Heights", "Ann Arbor", "Lansing",
        "Dearborn", "Clinton Township", "Canton Township", "Macomb Township", "Livonia", "Troy",
        "Farmington Hills", "Westland", "Shelby Township", "Wyoming", "Flint", "Rochester Hills",
        "Southfield", "Kalamazoo", "Waterford Township", "Novi", "West Bloomfield Township",
        "Pontiac", "Taylor",
    ],
    "MN": [
        "Minneapolis", "St. Paul", "Rochester", "Bloomington", "Duluth", "Brooklyn Park",
        "Woodbury", "Lakeville", "Plymouth", "Blaine", "Maple Grove", "St. Cloud", "Eagan",
        "Burnsville", "Coon Rapids", "Eden Prairie", "Apple Valley", "Edina", "Minnetonka",
        "Shakopee", "St. Louis Park", "Moorhead", "Mankato", "Cottage Grove", "Maplewood",
    ],
    "MS": [
        "Jackson", "Gulfport", "Southaven", "Hattiesburg", "Biloxi", "Olive Branch", "Tupelo",
        "Meridian", "Pearl", "Madison", "Oxford", "Horn Lake", "Brandon", "Clinton", "Greenville",
        "Starkville", "Ridgeland", "Columbus", "Pascagoula", "Vicksburg", "Hernando",
        "Ocean Springs", "Gautier", "Laurel", "Long Beach",
    ],
    "MO": [
        "Kansas City", "St. Louis", "Springfield", "Columbia", "Independence", "Lee's Summit",
        "O'Fallon", "St. Charles", "St. Joseph", "St. Peters", "Blue Springs", "Joplin",
        "Florissant", "Wentzville", "Chesterfield", "Jefferson City", "Cape Girardeau",
        "Oakville", "Wildwood", "University City", "Liberty", "Ballwin", "Kirkwood", "Mehlville",
        "Raytown",
    ],
    "MT": [
        "Billings", "Missoula", "Great Falls", "Bozeman", "Helena", "Butte-Silver Bow",
        "Kalispell", "Belgrade", "Helena Valley Southeast", "Anaconda-Deer Lodge County",
        "Whitefish", "Livingston", "Havre", "Evergreen", "Miles City", "Helena Valley West Central",
        "Lockwood", "Laurel", "Lewistown", "Sidney", "Four Corners", "Columbia Falls", "Polson",
        "Hamilton", "Bigfork",
    ],
    "NE": [
        "Omaha", "Lincoln", "Bellevue", "Grand Island", "Kearney", "Fremont", "Norfolk",
        "Columbus", "Hastings", "Papillion", "North Platte", "La Vista", "Scottsbluff",
        "South Sioux City", "Beatrice", "Lexington", "Chalco", "Gretna", "Gering", "York",
        "Blair", "Seward", "Alliance", "Crete", "Nebraska City",
    ],
    "NV": [
        "Las Vegas", "Henderson", "North Las Vegas", "Reno", "Enterprise", "Spring Valley",
        "Sunrise Manor", "Paradise", "Sparks", "Carson City", "Whitney", "Pahrump", "Winchester",
        "Summerlin South", "Fernley", "Mesquite", "Sun Valley", "Elko", "Spanish Springs",
        "Dayton", "Spring Creek", "Boulder City", "Gardnerville Ranchos", "Cold Springs", "Fallon",
    ],
    "NH": [
        "Manchester", "Nashua", "Concord", "Dover", "Derry", "Rochester", "Salem", "Merrimack",
        "Londonderry", "Hudson", "Bedford", "Portsmouth", "Keene", "Goffstown", "Laconia",
        "Milford", "Windham", "Hampton", "Exeter", "Lebanon", "Hooksett", "Durham", "Pelham",
        "Claremont", "Somersworth",
    ],
    "NJ": [
        "Newark", "Jersey City", "Paterson", "Lakewood", "Elizabeth", "Edison", "Woodbridge",
        "Toms River", "Hamilton", "Trenton", "Clifton", "Cherry Hill", "Brick", "Bayonne",
        "East Orange", "Passaic", "Camden", "Old Bridge", "Franklin Township",
        "Gloucester Township", "Middletown", "Union City", "Union", "Vineland", "Piscataway",
    ],
    "NM": [
        "Albuquerque", "Las Cruces", "Rio Rancho", "Santa Fe", "Roswell", "Farmington", "Hobbs",
        "Clovis", "South Valley", "Carlsbad", "Alamogordo", "Los Lunas", "Gallup",
        "Sunland Park", "Chaparral", "Deming", "Los Alamos", "Artesia", "Las Vegas", "Portales",
        "Lovington", "North Valley", "Espanola", "Silver City", "Bernalillo",
    ],
    "NY": [
        "New York City", "Buffalo", "Yonkers", "Rochester", "Syracuse", "Albany", "New Rochelle",
        "Mount Vernon", "Schenectady", "Utica", "White Plains", "Troy", "Niagara Falls",
        "Binghamton", "Long Beach", "Middletown", "Saratoga Springs", "Rome", "Newburgh",
        "Ithaca", "Poughkeepsie", "Glen Cove", "Elmira", "Auburn", "Watertown",
    ],
    "NC": [
        "Charlotte", "Raleigh", "Greensboro", "Durham", "Winston-Salem", "Fayetteville", "Cary",
        "Wilmington", "High Point", "Concord", "Greenville", "Asheville", "Gastonia", "Apex",
        "Jacksonville", "Huntersville", "Chapel Hill", "Kannapolis", "Burlington", "Wake Forest",
        "Mooresville", "Rocky Mount", "Holly Springs", "Fuquay-Varina", "Wilson",
    ],
    "ND": [
        "Fargo", "Bismarck", "Grand Forks", "Minot", "West Fargo", "Williston", "Dickinson",
        "Mandan", "Jamestown", "Wahpeton", "Horace", "Devils Lake", "Valley City",
        "Watford City", "Lincoln", "Grafton", "Beulah", "New Town", "Casselton", "Rugby",
        "Hazen", "Tioga", "Lisbon", "Bottineau",
    ],
    "OH": [
        "Columbus", "Cleveland", "Cincinnati", "Toledo", "Akron", "Dayton", "Parma", "Canton",
        "Lorain", "Hamilton", "Youngstown", "Springfield", "Kettering", "Elyria", "Middletown",
        "Newark", "Cuyahoga Falls", "Dublin", "Lakewood", "Beavercreek", "Euclid", "Delaware",
        "Mansfield", "Mentor", "Grove City",
    ],
    "OK": [
        "Oklahoma City", "Tulsa", "Norman", "Broken Arrow", "Edmond", "Lawton", "Moore",
        "Midwest City", "Stillwater", "Enid", "Owasso", "Bartlesville", "Muskogee", "Bixby",
        "Shawnee", "Jenks", "Yukon", "Mustang", "Ardmore", "Ponca City", "Sapulpa", "Duncan",
        "Durant", "El Reno", "Del City",
    ],
    "OR": [
        "Portland", "Salem", "Eugene", "Hillsboro", "Gresham", "Bend", "Beaverton", "Medford",
        "Corvallis", "Springfield", "Tigard", "Albany", "Aloha", "Lake Oswego", "Redmond",
        "Grants Pass", "Keizer", "Oregon City", "McMinnville", "Bethany", "Woodburn",
        "Happy Valley", "Tualatin", "Wilsonville", "Forest Grove",
    ],
    "PA": [
        "Philadelphia", "Pittsburgh", "Allentown", "Reading", "Erie", "Bethlehem", "Scranton",
        "Lancaster", "Harrisburg", "York", "Wilkes-Barre", "Altoona", "State College",
        "Norristown", "Chester", "Easton", "Hazleton", "Williamsport", "Lebanon", "New Castle",
        "Phoenixville", "Johnstown", "Washington", "Meadville", "Latrobe",
    ],
    "RI": [
        "Providence", "Cranston", "Warwick", "Pawtucket", "East Providence", "Woonsocket",
        "Cumberland", "Coventry", "North Providence", "South Kingstown", "West Warwick",
        "Johnston", "North Kingstown", "Newport", "Lincoln", "Central Falls", "Westerly",
        "Smithfield", "Bristol", "Portsmouth", "Burrillville", "Barrington", "Middletown",
        "Tiverton", "East Greenwich",
    ],
    "SC": [
        "Charleston", "Columbia", "North Charleston", "Mount Pleasant", "Rock Hill",
        "Greenville", "Summerville", "Goose Creek", "Greer", "Sumter", "Myrtle Beach",
        "Florence", "Fort Mill", "Spartanburg", "Bluffton", "Hilton Head Island", "Aiken",
        "Mauldin", "Carolina Forest", "Conway", "Anderson", "Simpsonville", "Easley",
        "North Augusta", "Lexington",
    ],
    "SD": [
        "Sioux Falls", "Rapid City", "Aberdeen", "Brookings", "Watertown", "Yankton", "Mitchell",
        "Huron", "Spearfish", "Box Elder", "Pierre", "Vermillion", "Brandon", "Harrisburg",
        "Tea", "Sturgis", "Rapid Valley", "Madison", "Belle Fourche", "Dakota Dunes",
        "Dell Rapids", "Hot Springs", "Hartford", "Milbank", "Mobridge",
    ],
    "TN": [
        "Nashville", "Memphis", "Knoxville", "Chattanooga", "Clarksville", "Murfreesboro",
        "Franklin", "Johnson City", "Jackson", "Smyrna", "Hendersonville", "Spring Hill",
        "Kingsport", "Gallatin", "Lebanon", "Bartlett", "Collierville", "Cleveland", "Columbia",
        "Mount Juliet", "Brentwood", "La Vergne", "Germantown", "Cookeville", "Oak Ridge",
    ],
    "TX": [
        "Houston", "San Antonio", "Dallas", "Fort Worth", "Austin", "El Paso", "Arlington",
        "Corpus Christi", "Plano", "Lubbock", "Laredo", "Irving", "Garland", "Frisco",
        "McKinney", "Grand Prairie", "Amarillo", "Brownsville", "Denton", "Killeen", "McAllen",
        "Mesquite", "Midland", "Waco", "Pasadena",
    ],
    "UT": [
        "Salt Lake City", "West Valley City", "West Jordan", "Provo", "St. George", "Lehi",
        "Orem", "Sandy", "Ogden", "South Jordan", "Layton", "Eagle Mountain", "Saratoga Springs",
        "Herriman", "Millcreek", "Taylorsville", "Logan", "Murray", "Draper", "Spanish Fork",
        "Riverton", "Bountiful", "Tooele", "Cedar City", "American Fork",
    ],
    "VT": [
        "Burlington", "South Burlington", "Colchester", "Rutland", "Bennington", "Brattleboro",
        "Essex", "Hartford", "Essex Junction", "Milton", "Williston", "Middlebury", "Springfield",
        "Winooski", "Shelburne", "Barre", "Montpelier", "St. Johnsbury", "St. Albans", "Swanton",
        "Morristown", "Northfield", "Lyndon",
    ],
    "VA": [
        "Virginia Beach", "Chesapeake", "Arlington", "Richmond", "Norfolk", "Newport News",
        "Alexandria", "Hampton", "Suffolk", "Roanoke", "Portsmouth", "Lynchburg", "Dale City",
        "Centreville", "Reston", "Woodbridge", "McLean", "Harrisonburg", "Leesburg", "Tuckahoe",
        "Ashburn", "Lake Ridge", "Blacksburg", "Manassas", "Charlottesville",
    ],
    "WA": [
        "Seattle", "Tacoma", "Spokane", "Vancouver", "Bellevue", "Kent", "Everett",
        "Spokane Valley", "Renton", "Federal Way", "Kirkland", "Yakima", "Bellingham",
        "Kennewick", "Auburn", "Redmond", "Pasco", "Marysville", "South Hill", "Shoreline",
        "Richland", "Sammamish", "Lakewood", "Lacey", "Olympia",
    ],
    "WV": [
        "Charleston", "Huntington", "Morgantown", "Parkersburg", "Wheeling", "Martinsburg",
        "Fairmont", "Weirton", "Beckley", "Clarksburg", "South Charleston", "Vienna",
        "St. Albans", "Charles Town", "Bridgeport", "Bluefield", "Moundsville", "Oak Hill",
        "Hurricane", "Ranson", "Dunbar", "Elkins", "Nitro", "Princeton", "Buckhannon",
    ],
    "WI": [
        "Milwaukee", "Madison", "Green Bay", "Kenosha", "Racine", "Appleton", "Eau Claire",
        "Waukesha", "Oshkosh", "Janesville", "West Allis", "La Crosse", "Sheboygan", "Wauwatosa",
        "Fond du Lac", "Menomonee Falls", "Brookfield", "Wausau", "Sun Prairie", "New Berlin",
        "Oak Creek", "Greenfield", "Franklin", "Beloit", "Fitchburg",
    ],
    "WY": [
        "Cheyenne", "Casper", "Gillette", "Laramie", "Rock Springs", "Sheridan", "Evanston",
        "Green River", "Riverton", "Jackson", "Cody", "Rawlins", "Lander", "Powell", "Ranchettes",
        "Douglas", "Torrington", "Buffalo", "Worland", "Mills", "South Greeley",
        "Fox Farm-College", "Wheatland", "Newcastle", "Bar Nunn",
    ],
}
